# Cambiar el project key por el formato solicitado por el profesor: nombre_apellido_t1.
# Poner las exclusiones de codigo necesarias e incluir tests/cobertura.

sonar.projectKey=Hanks_Vargas_T1
sonar.sources=src
sonar.exclusions=.venv/**,__pycache__/**,.pytest_cache/**,.coverage,coverage.xml
sonar.coverage.exclusions=src/rewards/infrastructure/messaging/**,src/rewards/common/config.py,src/rewards/services/**
sonar.host.url=https://sonarqube.ingsoftware.lat/

# CONFIGURACION DE PRUEBAS Y COBERTURA
sonar.tests=tests
sonar.test.inclusions=tests/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
